---
title: "Assignment 1: Introduction to Data Exploration"
author: "James Tauber"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Exploration. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I don't have very much data analytics experience. I did a very limited amount of R work during my undergrad, and worked at the beginning of the summer to try and train myself to learn it a little bit more before my degree started informally. As part of that I downloaded and made a github account.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident that I'll be able to figure out R at an appropriate speed.

3. Are there any components of the course about which you feel apprehensive?

> Answer: Probably the flipped format. I;m not really used to it yet and have never taken a flipped course before.


## 2) GitHub

Go over Tasks 1.1. through 1.6 on Course Setup page. Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/j-tauber/EDE_R_Lab_F26

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
